# Pipeline includes two stages
# MAIN_STAGE: All tested and working tasks
# DEV_STAGE: Useful if you just want to test one single task without running the entire pipeline.


stages:

- stage: 'Prepare'
  displayName: 'Prepare'

  jobs:
  - job: 'Prep'
    steps:
    - task: PowerShell@2
      name: Verify_Parameters
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Please review the below parameters:"

- stage: 'Main_Stage'
  displayName: 'Main Stage'
  dependsOn: 'Prepare'
  condition: succeeded('Prepare')
  jobs:
  - job: 'Main_Stage'
    pool:
      vmImage: ubuntu-latest2
    timeoutInMinutes: 120
    continueOnError: false
    steps:
    - script: echo Hello
      displayName: 'Task 1'

    - script: echo Hello
      displayName: 'Task 2'
    


- stage: 'Dev_Stage'
  displayName: 'Dev Stage'
  dependsOn: 'Prepare'
  condition: succeeded('Prepare')
  jobs:
  - job: 'Dev_Stage'
    pool:
      vmImage: ubuntu-latest2
    timeoutInMinutes: 120
    continueOnError: false
    steps:
    - script: echo Hello
      displayName: 'Task 1'

    - script: echo Hello
      displayName: 'Task 2'